import { Resources } from "../../config/Resources";

export const topAthletes = [
  {
    id: "1",
    profile: Resources.images.TopAthletes.Top100Athletes.player1,
    name: "Ged ",
    lastName: "Doughton",
    TimeOfPlay: "1974-1975",
  },
  {
    id: "2",
    profile: Resources.images.TopAthletes.Top100Athletes.player2,
    name: "Ged ",
    lastName: "Doughton",
    TimeOfPlay: "1974-1975",
  },
  {
    id: "3",
    profile: Resources.images.TopAthletes.Top100Athletes.player3,
    name: "Ged ",
    lastName: "Doughton",
    TimeOfPlay: "1974-1975",
  },
  {
    id: "4",
    profile: Resources.images.TopAthletes.Top100Athletes.player4,
    name: "Ged ",
    lastName: "Doughton",
    TimeOfPlay: "1974-1975",
  },
  {
    id: "5",
    profile: Resources.images.TopAthletes.Top100Athletes.player5,
    name: "Ged ",
    lastName: "Doughton",
    TimeOfPlay: "1974-1975",
  },
  {
    id: "6",
    profile: Resources.images.TopAthletes.Top100Athletes.player1,
    name: "Ged ",
    lastName: "Doughton",
    TimeOfPlay: "1974-1975",
  },
  {
    id: "7",
    profile: Resources.images.TopAthletes.Top100Athletes.player2,
    name: "Ged ",
    lastName: "Doughton",
    TimeOfPlay: "1974-1975",
  },
  {
    id: "8",
    profile: Resources.images.TopAthletes.Top100Athletes.player3,
    name: "Ged ",
    lastName: "Doughton",
    TimeOfPlay: "1974-1975",
  },
  {
    id: "9",
    profile: Resources.images.TopAthletes.Top100Athletes.player4,
    name: "Ged ",
    lastName: "Doughton",
    TimeOfPlay: "1974-1975",
  },
  {
    id: "10",
    profile: Resources.images.TopAthletes.Top100Athletes.player5,
    name: "Ged ",
    lastName: "Doughton",
    TimeOfPlay: "1974-1975",
  },
  {
    id: "11",
    profile: Resources.images.TopAthletes.Top100Athletes.player1,
    name: "Ged ",
    lastName: "Doughton",
    TimeOfPlay: "1974-1975",
  },
  {
    id: "12",
    profile: Resources.images.TopAthletes.Top100Athletes.player2,
    name: "Ged ",
    lastName: "Doughton",
    TimeOfPlay: "1974-1975",
  },
  {
    id: "13",
    profile: Resources.images.TopAthletes.Top100Athletes.player3,
    name: "Ged ",
    lastName: "Doughton",
    TimeOfPlay: "1974-1975",
  },
  {
    id: "14",
    profile: Resources.images.TopAthletes.Top100Athletes.player4,
    name: "Ged ",
    lastName: "Doughton",
    TimeOfPlay: "1974-1975",
  },
  {
    id: "15",
    profile: Resources.images.TopAthletes.Top100Athletes.player5,
    name: "Ged ",
    lastName: "Doughton",
    TimeOfPlay: "1974-1975",
  },
];
