const base = "/images";

export const Resources = {
  images: {
    ProductDetails: {
      accessories: {
        accessory1: `${base}/ProductDetails/accessories/accessory1.png`,
      },

      image: {
        backgroundImage: `${base}/ProductDetails/accessories/accessoriesBackground.png`,
      },
      ProductSlider: `${base}/ProductDetails/ProductSlider.png`,
      AthleteProfile: `${base}/ProductDetails/AthleteProfile.png`,
      GedDoughton: `${base}/ProductDetails/GedDoughton.png`,
      NotEstateProfile: `${base}/ProductDetails/NotEstateProfile.svg`,
      ProductImage: `${base}/ProductDetails/ProductImage.png`,
      ZoomedProductImage: `${base}/ProductDetails/ZoomedProductImage.png`,
      Product: `${base}/ProductDetails/product.png`,
      Trending: `${base}/ProductDetails/trending.png`,
      Rating: `${base}/ProductDetails/Rating.png`,
      ProductSmall: `${base}/ProductDetails/productSmall.png`,
      FanCam: {
        fanCam: `${base}/ProductDetails/FanCam/fanCam.png`,
        fanCamera: `${base}/ProductDetails/FanCam/fanCamera.svg`,
      },
    },
    LandingPage: {
      legacyMobile: `${base}/LandingPage/Legacy/legacy-mobile.png`,
      legacy: `${base}/LandingPage/Legacy/legacy.png`,
      family: `${base}/LandingPage/Support/family.png`,
      topSellers: {
        product1: `${base}/Landing/topSellers/product1.png`,
        product2: `${base}/Landing/topSellers/product2.png`,
        product3: `${base}/Landing/topSellers/product3.png`,
        product4: `${base}/Landing/topSellers/product4.png`,
        product5: `${base}/Landing/topSellers/product5.png`,
        product6: `${base}/Landing/topSellers/product6.png`,
        product7: `${base}/Landing/topSellers/product7.png`,
      },
      image: {
        backgroundImage: `${base}/Landing/topSellers/topSellersBackground.png`,
      },
      background: `${base}/LandingPage/JoinEstate.svg`,
      playground: `${base}/LandingPage/playground.png`,
    },
    Navbar: {
      NavbarMenu: `${base}/Navbar/NavbarMenu.svg`,
      AthleticEstateHeaderIcon: `${base}/Navbar/AthleticEstateHeaderIcon.svg`,
      SearchIcon: `${base}/Navbar/SearchIcon.svg`,
      Cart: `${base}/Navbar/Cart.svg`,
      SearchinMenu: `${base}/Navbar/SearchinMenu.svg`,
      BackArrow: `${base}/Navbar/BackArrow.svg`,
      Info: `${base}/Navbar/Info.svg`,
      Tag: `${base}/Navbar/Tag.svg`,
      Trpohie: `${base}/Navbar/Trpohie.svg`,
      UserCircle: `${base}/Navbar/UserCircle.svg`,
      Bell: `${base}/Navbar/Bell.svg`,
      Transport: `${base}/Navbar/Transport.svg`,
      CartJersey1: `${base}/Navbar/Jersey.png`,
      CartJersey2: `${base}/Navbar/Jersey2.png`,
      PayPal: `${base}/Navbar/PayPal.png`,
      EmptyCartLogo: `${base}/Navbar/ShoppingCartSimple.svg`,
    },
    productList: {
      hamBurger: `${base}/productList/hamBurger.svg`,
      offerTag: `${base}/productList/offerTag.svg`,
      notFoundLogo: `${base}/productList/notFound.png`,
      jerseys: {
        blueJersey: `${base}/productList/jerseys/blueJersey.png`,
        redJersey: `${base}/productList/jerseys/redJersey.png`,
        skyJersey: `${base}/productList/jerseys/skyJersey.png`,
        blackJersey: `${base}/productList/jerseys/blackJersey.png`,
      },
    },
    Account: {
      payPal: `${base}/UserCheckout/payPal.svg`,
      CreditCardIcon: `${base}/UserAccount/CreditCardIcon.svg`,
    },
    AboutUs: {
      ourStoryBanner: `${base}/AboutUs/OurStoryBanner.png`,
      team: {
        rachelHills: `${base}/AboutUs/Team/rachelHills.png`,
        michaelSmith: `${base}/AboutUs/Team/michaelSmith.png`,
        johnWalker: `${base}/AboutUs/Team/johnWalker.png`,
        natalieEdwards: `${base}/AboutUs/Team/natalieEdwards.png`,
        sarahWoods: `${base}/AboutUs/Team/sarahWoods.png`,
        edwardAnderson: `${base}/AboutUs/Team/edwardAnderson.png`,
      },
    },

    SignInSignUp: {
      MailLogo: `${base}/SignInSignUp/mailLogo.png`,
    },
    TopAthletes: {
      CoryJames: `${base}/TopAthletes/coryJames.png`,
      universityCard: {
        player1: `${base}/TopAthletes/universityCard/player1.png`,
        player2: `${base}/TopAthletes/universityCard/player2.png`,
        player3: `${base}/TopAthletes/universityCard/player3.png`,
        player4: `${base}/TopAthletes/universityCard/player4.png`,
        player5: `${base}/TopAthletes/universityCard/player5.png`,
      },
      Top100Athletes: {
        AthleteImage: `${base}/TopAthletes/Top100Athletes/athleteImage.png`,
        player1: `${base}/TopAthletes/Top100Athletes/Player1.svg`,
        player2: `${base}/TopAthletes/Top100Athletes/Player2.svg`,
        player3: `${base}/TopAthletes/Top100Athletes/Player3.svg`,
        player4: `${base}/TopAthletes/Top100Athletes/Player4.svg`,
        player5: `${base}/TopAthletes/Top100Athletes/Player5.svg`,
      },
    },
    TrackingPage: {
      groundDesktop: `${base}/TrackingPage/groundDesktop.png`,
      groundMobile: `${base}/TrackingPage/groundMobile.png`,
      weightRoom: `${base}/TrackingPage/weightRoom.png`,
      lockerRoom: `${base}/TrackingPage/lockerRoom.png`,
      airplane: `${base}/TrackingPage/airplane.png`,
      paparazzi: `${base}/TrackingPage/paparazzi.png`,
      onTheField: `${base}/TrackingPage/onTheField.png`,
      player1: `${base}/TrackingPage/player1.png`,
      player2: `${base}/TrackingPage/player2.png`,
      athleteNo: `${base}/TrackingPage/athleteNo.png`,
      athleteNoDesktop: `${base}/TrackingPage/athleteNoDesktop.png`,
    },
    OrderConfirmation: {
      ShoppingCart: `${base}/OrderConfirmation/ShoppingCart.png`,
    },
    Community: {
      AthleteProfile: `${base}/Community/AthleteProfile.png`,
      AddMessage: `${base}/Community/AddMessage.svg`,
    },
    AthleticEstateNews: {
      personImage: `${base}/AthleticEstateNews/person.png`,
    },
    NavTab: {
      community: `${base}/NavTab/community.png`,
      news: `${base}/NavTab/news.png`,
      dashboard: `${base}/NavTab/dashboard.png`,
      revenue: `${base}/NavTab/revenue.png`,
      communityHighlighted: `${base}/NavTab/communityHighlighted.png`,
      newsHighlighted: `${base}/NavTab/newsHighlighted.png`,
      dashboardHighlighted: `${base}/NavTab/dashboardHighlighted.png`,
      revenueHighlighted: `${base}/NavTab/revenueHighlighted.png`,
      bank: `${base}/NavTab/bank.png`,
      paidToYouMobile: `${base}/NavTab/paidToYouMobile.png`,
      paidToYouDesktop: `${base}/NavTab/paidToYouDesktop.png`,
    },
    AccountSetup: {
      bank: `${base}/AccountSetup/bank.png`,
      editIcon: `${base}/AccountSetup/editIcon.png`,
      ellipse: `${base}/AccountSetup/ellipse.png`,
    },
    AthleteDashboard: {
      dashboard: `${base}/AthleteDashboard/dashboard.png`,
      community: `${base}/AthleteDashboard/community.png`,
      revenue: `${base}/AthleteDashboard/revenue.png`,
      aeNews: `${base}/AthleteDashboard/aeNews.png`,
      user: `${base}/AthleteDashboard/user.png`,
      user2: `${base}/AthleteDashboard/user2.png`,
      user3: `${base}/AthleteDashboard/user3.png`,
      user4: `${base}/AthleteDashboard/user4.png`,
      user5: `${base}/AthleteDashboard/user5.png`,
      player1: `${base}/AthleteDashboard/player1.png`,
      player2: `${base}/AthleteDashboard/player2.png`,
      player3: `${base}/AthleteDashboard/player3.png`,
      player4: `${base}/AthleteDashboard/player4.png`,
      player5: `${base}/AthleteDashboard/player5.png`,
    },
    JoinAE:`${base}/JoinAE/Loremplayer.png`,
    Athlete: {
      ConfirmIdentity: {
        UploadDocument: `${base}/IdentityConfirmation/UploadDocument.svg`,
        Document: `${base}/IdentityConfirmation/Document.svg`,
      },
    },
  },
};
