import { Resources } from "../../../config/Resources";

export const Top100AthletesData = [
  {
    id:"1",
    athlete_image: Resources.images.TopAthletes.Top100Athletes.AthleteImage,
    name: "CORY JAMES",
    no: "#17",
    college: "Lorem ipsum dolor",
    sport: "Lorem",
    year: "2018-2020 | "

  },
  {
    id:"2",
    athlete_image: Resources.images.TopAthletes.Top100Athletes.AthleteImage,
    name: "CORY JAMES",
    no: "#17",
    college: "Lorem ipsum dolor",
    sport: "Lorem",
    year: "2018-2020 | ",
  },
  {
    id:"3",
    athlete_image: Resources.images.TopAthletes.Top100Athletes.AthleteImage,
    name: "CORY JAMES",
    no: "#17",
    college: "Lorem ipsum dolor",
    sport: "Lorem",
    year: "2018-2020 | ",
  },
  {
    id:"4",
    athlete_image: Resources.images.TopAthletes.Top100Athletes.AthleteImage,
    name: "CORY JAMES",
    no: "#17",
    college: "Lorem ipsum dolor",
    sport: "Lorem",
    year: "2018-2020 | ",
  },
  {
    id:"5",
    athlete_image: Resources.images.TopAthletes.Top100Athletes.AthleteImage,
    name: "CORY JAMES",
    no: "#17",
    college: "Lorem ipsum dolor",
    sport: "Lorem",
    year: "2018-2020 | ",
  },
  {
    id:"6",
    athlete_image: Resources.images.TopAthletes.Top100Athletes.AthleteImage,
    name: "CORY JAMES",
    no: "#17",
    college: "Lorem ipsum dolor",
    sport: "Lorem",
    year: "2018-2020 | ",
  },
  {
    id:"7",
    athlete_image: Resources.images.TopAthletes.Top100Athletes.AthleteImage,
    name: "CORY JAMES",
    no: "#17",
    college: "Lorem ipsum dolor",
    sport: "Lorem",
    year: "2018-2020 | ",
  },
  {
    id:"8",
    athlete_image: Resources.images.TopAthletes.Top100Athletes.AthleteImage,
    name: "CORY JAMES",
    no: "#17",
    college: "Lorem ipsum dolor",
    sport: "Lorem",
    year: "2018-2020 | ",
  },
  {
    id:"9",
    athlete_image: Resources.images.TopAthletes.Top100Athletes.AthleteImage,
    name: "CORY JAMES",
    no: "#17",
    college: "Lorem ipsum dolor",
    sport: "Lorem",
    year: "2018-2020 | ",
  },
  {
    id:"10",
    athlete_image: Resources.images.TopAthletes.Top100Athletes.AthleteImage,
    name: "CORY JAMES",
    no: "#17",
    college: "Lorem ipsum dolor",
    sport: "Lorem",
    year: "2018-2020 | ",
  },
];
