export const UploadedDocumentsData = [
  {
    id: "driverL",
    date: "01/01/2021",
    fileName: "Lorem Ipsum",
    size: "14.65 KB",
    status: "Completed",
    document: "Driver’s License",
    type: ".png",
  },
  {
    id: "driverL_2",
    date: "01/01/2021",
    fileName: "Lorem Ipsum",
    size: "14.65 KB",
    status: "Completed",
    document: "Driver’s License",
    type: ".png",
  },
  {
    id: "passP",
    date: "01/01/2021",
    fileName: "Lorem Ipsum",
    size: "14.65 KB",
    status: "Completed",
    document: "Passport",
    type: ".png",
  },
  {
    id: "milId",
    date: "01/01/2021",
    fileName: "Lorem Ipsum",
    size: "14.65 KB",
    status: "Completed",
    document: "Military ID",
    type: ".png",
  },

  {
    id: "collegeD",
    date: "01/01/2021",
    fileName: "Lorem Ipsum",
    size: "14.65 KB",
    status: "Completed",
    document: "College Degree",
    type: ".png",
  },
  {
    id: "collegeD_1",
    date: "01/01/2021",
    fileName: "Lorem Ipsum",
    size: "14.65 KB",
    status: "Completed",
    document: "College Degree",
    type: ".png",
  },
  {
    id: "driverL_3",
    date: "01/01/2021",
    fileName: "Lorem Ipsum",
    size: "14.65 KB",
    status: "Completed",
    document: "Driver’s License",
    type: ".png",
  },
  {
    id: "passP",
    date: "01/01/2021",
    fileName: "Lorem Ipsum",
    size: "14.65 KB",
    status: "Completed",
    document: "Passport",
    type: ".png",
  },
  {
    id: "passP_2",
    date: "01/01/2021",
    fileName: "Lorem Ipsum",
    size: "14.65 KB",
    status: "Completed",
    document: "Passport",
    type: ".png",
  },
  {
    id: "schoolId",
    date: "01/01/2021",
    fileName: "Lorem Ipsum",
    size: "14.65 KB",
    status: "Completed",
    document: "School ID",
    type: ".png",
  },
];
